# tests/test_pipeline_integration.py

import unittest
import sys
import pathlib
import pandas as pd

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from src.features import assemble_feature_frame
from src.registry import get_model_names, make_model, get_search_space


class TestPipelineIntegration(unittest.TestCase):
    """
    Integration test to validate that:
      - real dataset can be read correctly,
      - feature engineering runs without errors,
      - model pipelines can be constructed from the registry,
      - hyperparameter search spaces are defined.

    This test does NOT fit or predict with any model.
    It simply ensures all project components are wired correctly.
    """

    def setUp(self):
        data_path = ROOT / "vehicles.csv"
        self.assertTrue(data_path.exists(), "Expected dataset not found at /vehicles.csv")
        df = pd.read_csv(data_path)
        self.df = df.head(50)
        required_cols = ["price", "year", "odometer"]
        for col in required_cols:
            self.assertIn(col, self.df.columns, f"Dataset missing required column '{col}'")

    def test_pipeline_on_real_data_sample(self):
        """
        Run the real dataset through feature assembly and pipeline construction.
        """
        X, num_cols, cat_cols = assemble_feature_frame(
            self.df, include_engineered=True
        )

        # Basic checks
        self.assertEqual(len(X), len(self.df))
        self.assertIsInstance(X, pd.DataFrame)
        self.assertGreater(len(num_cols), 0, "Numeric feature list unexpectedly empty")

        for col in num_cols:
            self.assertIn(col, X.columns)

        for col in cat_cols:
            self.assertIn(col, X.columns)

        model_names = get_model_names()
        self.assertGreater(len(model_names), 0, "Model registry returned no models")

        chosen_model = "gbr" if "gbr" in model_names else model_names[0]

        pipeline = make_model(
            chosen_model,
            num_cols=num_cols,
            cat_cols=cat_cols,
        )

        self.assertTrue(hasattr(pipeline, "fit"))
        self.assertTrue

# Part of this file was generated by ChatGPT 5.1