Buick_MODEL_MAP = {
  "allure": "Allure",
  "cascada": "Cascada",
  "centry": "Century",
  "century": "Century",
  "cxl": "CXL",
  "emcore": "Encore",
  "encalve": "Enclave",
  "enclave": "Enclave",
  "encore": "Encore",
  "enlave": "Enclave",
  "envision": "Envision",
  "envlave": "Enclave",
  "gn": "GN",
  "grand": "Grand National",
  "inc": "Regal",
  "la": "LaCrosse",
  "lacross": "LaCrosse",
  "lacrosse": "LaCrosse",
  "lasabre": "LeSabre",
  "le": "LeSabre",
  "lecern": "Lucerne",
  "lecerne": "Lucerne",
  "lesabre": "LeSabre",
  "lucern": "Lucerne",
  "lucerne": "Lucerne",
  "park": "Park Avenue",
  "rainer": "Rainier",
  "rainier": "Rainier",
  "ranier": "Rainier",
  "reatta": "Reatta",
  "regal": "Regal",
  "rendevous": "Rendezvous",
  "rendezvous": "Rendezvous",
  "renzendeous": "Rendezvous",
  "rivera": "Riviera",
  "riveria": "Riviera",
  "riviera": "Riviera",
  "roadmaster": "Roadmaster",
  "skylark": "Skylark",
  "terazza": "Terraza",
  "terazza": "Terraza",
  "verano": "Verano",
  "verao": "Verano",
  "verrano": "Verano"
}
